; Generated by the schema compiler.
skin_runtime: equ 0
skin_custom: equ 1
skin_artdeco: equ 1
skin_seventies: equ 0
live_test_mode: equ 1
    include "../ui/nineties/profile.inc"
    include "jukebox_modules.inc"
    include "../ui/nineties/widgets.inc"
    include "jukebox_start.inc"
