
num_samples:    equ 20

; Sample dictionary (pointer, bufferId)
sample_dictionary:
    dl fn_038
    db 38
    dl fn_042
    db 42
    dl fn_046
    db 46
    dl fn_050
    db 50
    dl fn_054
    db 54
    dl fn_058
    db 58
    dl fn_062
    db 62
    dl fn_066
    db 66
    dl fn_070
    db 70
    dl fn_074
    db 74
    dl fn_078
    db 78
    dl fn_082
    db 82
    dl fn_086
    db 86
    dl fn_090
    db 90
    dl fn_096
    db 96
    dl fn_102
    db 102
    dl fn_106
    db 106
    dl fn_111
    db 111
    dl fn_128
    db 128
    dl fn_132
    db 132

; Sample filename strings
sample_filenames:
    fn_038:    asciz "piano_yamaha/038.wav"
    fn_042:    asciz "piano_yamaha/042.wav"
    fn_046:    asciz "piano_yamaha/046.wav"
    fn_050:    asciz "piano_yamaha/050.wav"
    fn_054:    asciz "piano_yamaha/054.wav"
    fn_058:    asciz "piano_yamaha/058.wav"
    fn_062:    asciz "piano_yamaha/062.wav"
    fn_066:    asciz "piano_yamaha/066.wav"
    fn_070:    asciz "piano_yamaha/070.wav"
    fn_074:    asciz "piano_yamaha/074.wav"
    fn_078:    asciz "piano_yamaha/078.wav"
    fn_082:    asciz "piano_yamaha/082.wav"
    fn_086:    asciz "piano_yamaha/086.wav"
    fn_090:    asciz "piano_yamaha/090.wav"
    fn_096:    asciz "piano_yamaha/096.wav"
    fn_102:    asciz "piano_yamaha/102.wav"
    fn_106:    asciz "piano_yamaha/106.wav"
    fn_111:    asciz "piano_yamaha/111.wav"
    fn_128:    asciz "piano_yamaha/128.wav"
    fn_132:    asciz "piano_yamaha/132.wav"
