
num_samples:    equ 81

; Sample dictionary (pointer, bufferId)
sample_dictionary:
    dl fn_025
    db 25
    dl fn_026
    db 26
    dl fn_027
    db 27
    dl fn_028
    db 28
    dl fn_029
    db 29
    dl fn_030
    db 30
    dl fn_031
    db 31
    dl fn_032
    db 32
    dl fn_033
    db 33
    dl fn_034
    db 34
    dl fn_035
    db 35
    dl fn_036
    db 36
    dl fn_037
    db 37
    dl fn_038
    db 38
    dl fn_039
    db 39
    dl fn_040
    db 40
    dl fn_041
    db 41
    dl fn_042
    db 42
    dl fn_043
    db 43
    dl fn_044
    db 44
    dl fn_045
    db 45
    dl fn_046
    db 46
    dl fn_047
    db 47
    dl fn_048
    db 48
    dl fn_049
    db 49
    dl fn_050
    db 50
    dl fn_051
    db 51
    dl fn_052
    db 52
    dl fn_053
    db 53
    dl fn_054
    db 54
    dl fn_055
    db 55
    dl fn_056
    db 56
    dl fn_057
    db 57
    dl fn_058
    db 58
    dl fn_059
    db 59
    dl fn_060
    db 60
    dl fn_061
    db 61
    dl fn_062
    db 62
    dl fn_063
    db 63
    dl fn_064
    db 64
    dl fn_065
    db 65
    dl fn_066
    db 66
    dl fn_067
    db 67
    dl fn_068
    db 68
    dl fn_069
    db 69
    dl fn_070
    db 70
    dl fn_071
    db 71
    dl fn_072
    db 72
    dl fn_073
    db 73
    dl fn_074
    db 74
    dl fn_075
    db 75
    dl fn_076
    db 76
    dl fn_077
    db 77
    dl fn_078
    db 78
    dl fn_079
    db 79
    dl fn_080
    db 80
    dl fn_081
    db 81
    dl fn_082
    db 82
    dl fn_083
    db 83
    dl fn_084
    db 84
    dl fn_085
    db 85
    dl fn_086
    db 86
    dl fn_087
    db 87
    dl fn_088
    db 88
    dl fn_089
    db 89
    dl fn_090
    db 90
    dl fn_091
    db 91
    dl fn_092
    db 92
    dl fn_093
    db 93
    dl fn_094
    db 94
    dl fn_095
    db 95
    dl fn_096
    db 96
    dl fn_097
    db 97
    dl fn_098
    db 98
    dl fn_099
    db 99
    dl fn_100
    db 100
    dl fn_101
    db 101
    dl fn_102
    db 102
    dl fn_103
    db 103
    dl fn_104
    db 104
    dl fn_105
    db 105

; Sample filename strings
sample_filenames:
    fn_025:    asciz "piano_sf2/025.wav"
    fn_026:    asciz "piano_sf2/026.wav"
    fn_027:    asciz "piano_sf2/027.wav"
    fn_028:    asciz "piano_sf2/028.wav"
    fn_029:    asciz "piano_sf2/029.wav"
    fn_030:    asciz "piano_sf2/030.wav"
    fn_031:    asciz "piano_sf2/031.wav"
    fn_032:    asciz "piano_sf2/032.wav"
    fn_033:    asciz "piano_sf2/033.wav"
    fn_034:    asciz "piano_sf2/034.wav"
    fn_035:    asciz "piano_sf2/035.wav"
    fn_036:    asciz "piano_sf2/036.wav"
    fn_037:    asciz "piano_sf2/037.wav"
    fn_038:    asciz "piano_sf2/038.wav"
    fn_039:    asciz "piano_sf2/039.wav"
    fn_040:    asciz "piano_sf2/040.wav"
    fn_041:    asciz "piano_sf2/041.wav"
    fn_042:    asciz "piano_sf2/042.wav"
    fn_043:    asciz "piano_sf2/043.wav"
    fn_044:    asciz "piano_sf2/044.wav"
    fn_045:    asciz "piano_sf2/045.wav"
    fn_046:    asciz "piano_sf2/046.wav"
    fn_047:    asciz "piano_sf2/047.wav"
    fn_048:    asciz "piano_sf2/048.wav"
    fn_049:    asciz "piano_sf2/049.wav"
    fn_050:    asciz "piano_sf2/050.wav"
    fn_051:    asciz "piano_sf2/051.wav"
    fn_052:    asciz "piano_sf2/052.wav"
    fn_053:    asciz "piano_sf2/053.wav"
    fn_054:    asciz "piano_sf2/054.wav"
    fn_055:    asciz "piano_sf2/055.wav"
    fn_056:    asciz "piano_sf2/056.wav"
    fn_057:    asciz "piano_sf2/057.wav"
    fn_058:    asciz "piano_sf2/058.wav"
    fn_059:    asciz "piano_sf2/059.wav"
    fn_060:    asciz "piano_sf2/060.wav"
    fn_061:    asciz "piano_sf2/061.wav"
    fn_062:    asciz "piano_sf2/062.wav"
    fn_063:    asciz "piano_sf2/063.wav"
    fn_064:    asciz "piano_sf2/064.wav"
    fn_065:    asciz "piano_sf2/065.wav"
    fn_066:    asciz "piano_sf2/066.wav"
    fn_067:    asciz "piano_sf2/067.wav"
    fn_068:    asciz "piano_sf2/068.wav"
    fn_069:    asciz "piano_sf2/069.wav"
    fn_070:    asciz "piano_sf2/070.wav"
    fn_071:    asciz "piano_sf2/071.wav"
    fn_072:    asciz "piano_sf2/072.wav"
    fn_073:    asciz "piano_sf2/073.wav"
    fn_074:    asciz "piano_sf2/074.wav"
    fn_075:    asciz "piano_sf2/075.wav"
    fn_076:    asciz "piano_sf2/076.wav"
    fn_077:    asciz "piano_sf2/077.wav"
    fn_078:    asciz "piano_sf2/078.wav"
    fn_079:    asciz "piano_sf2/079.wav"
    fn_080:    asciz "piano_sf2/080.wav"
    fn_081:    asciz "piano_sf2/081.wav"
    fn_082:    asciz "piano_sf2/082.wav"
    fn_083:    asciz "piano_sf2/083.wav"
    fn_084:    asciz "piano_sf2/084.wav"
    fn_085:    asciz "piano_sf2/085.wav"
    fn_086:    asciz "piano_sf2/086.wav"
    fn_087:    asciz "piano_sf2/087.wav"
    fn_088:    asciz "piano_sf2/088.wav"
    fn_089:    asciz "piano_sf2/089.wav"
    fn_090:    asciz "piano_sf2/090.wav"
    fn_091:    asciz "piano_sf2/091.wav"
    fn_092:    asciz "piano_sf2/092.wav"
    fn_093:    asciz "piano_sf2/093.wav"
    fn_094:    asciz "piano_sf2/094.wav"
    fn_095:    asciz "piano_sf2/095.wav"
    fn_096:    asciz "piano_sf2/096.wav"
    fn_097:    asciz "piano_sf2/097.wav"
    fn_098:    asciz "piano_sf2/098.wav"
    fn_099:    asciz "piano_sf2/099.wav"
    fn_100:    asciz "piano_sf2/100.wav"
    fn_101:    asciz "piano_sf2/101.wav"
    fn_102:    asciz "piano_sf2/102.wav"
    fn_103:    asciz "piano_sf2/103.wav"
    fn_104:    asciz "piano_sf2/104.wav"
    fn_105:    asciz "piano_sf2/105.wav"
