
num_samples:    equ 68

; Sample dictionary (pointer, bufferId)
sample_dictionary:
    dl fn_021
    db 21
    dl fn_022
    db 22
    dl fn_023
    db 23
    dl fn_024
    db 24
    dl fn_025
    db 25
    dl fn_026
    db 26
    dl fn_027
    db 27
    dl fn_028
    db 28
    dl fn_029
    db 29
    dl fn_030
    db 30
    dl fn_031
    db 31
    dl fn_032
    db 32
    dl fn_033
    db 33
    dl fn_034
    db 34
    dl fn_035
    db 35
    dl fn_036
    db 36
    dl fn_037
    db 37
    dl fn_038
    db 38
    dl fn_039
    db 39
    dl fn_040
    db 40
    dl fn_041
    db 41
    dl fn_042
    db 42
    dl fn_043
    db 43
    dl fn_044
    db 44
    dl fn_045
    db 45
    dl fn_046
    db 46
    dl fn_047
    db 47
    dl fn_048
    db 48
    dl fn_049
    db 49
    dl fn_050
    db 50
    dl fn_051
    db 51
    dl fn_052
    db 52
    dl fn_053
    db 53
    dl fn_054
    db 54
    dl fn_055
    db 55
    dl fn_056
    db 56
    dl fn_057
    db 57
    dl fn_058
    db 58
    dl fn_059
    db 59
    dl fn_060
    db 60
    dl fn_061
    db 61
    dl fn_062
    db 62
    dl fn_063
    db 63
    dl fn_064
    db 64
    dl fn_065
    db 65
    dl fn_066
    db 66
    dl fn_067
    db 67
    dl fn_068
    db 68
    dl fn_069
    db 69
    dl fn_070
    db 70
    dl fn_071
    db 71
    dl fn_072
    db 72
    dl fn_073
    db 73
    dl fn_074
    db 74
    dl fn_075
    db 75
    dl fn_076
    db 76
    dl fn_077
    db 77
    dl fn_078
    db 78
    dl fn_079
    db 79
    dl fn_080
    db 80
    dl fn_081
    db 81
    dl fn_082
    db 82
    dl fn_083
    db 83
    dl fn_084
    db 84
    dl fn_085
    db 85
    dl fn_086
    db 86
    dl fn_087
    db 87
    dl fn_088
    db 88

; Sample filename strings
sample_filenames:
    fn_021:    asciz "harpsichord/021.wav"
    fn_022:    asciz "harpsichord/022.wav"
    fn_023:    asciz "harpsichord/023.wav"
    fn_024:    asciz "harpsichord/024.wav"
    fn_025:    asciz "harpsichord/025.wav"
    fn_026:    asciz "harpsichord/026.wav"
    fn_027:    asciz "harpsichord/027.wav"
    fn_028:    asciz "harpsichord/028.wav"
    fn_029:    asciz "harpsichord/029.wav"
    fn_030:    asciz "harpsichord/030.wav"
    fn_031:    asciz "harpsichord/031.wav"
    fn_032:    asciz "harpsichord/032.wav"
    fn_033:    asciz "harpsichord/033.wav"
    fn_034:    asciz "harpsichord/034.wav"
    fn_035:    asciz "harpsichord/035.wav"
    fn_036:    asciz "harpsichord/036.wav"
    fn_037:    asciz "harpsichord/037.wav"
    fn_038:    asciz "harpsichord/038.wav"
    fn_039:    asciz "harpsichord/039.wav"
    fn_040:    asciz "harpsichord/040.wav"
    fn_041:    asciz "harpsichord/041.wav"
    fn_042:    asciz "harpsichord/042.wav"
    fn_043:    asciz "harpsichord/043.wav"
    fn_044:    asciz "harpsichord/044.wav"
    fn_045:    asciz "harpsichord/045.wav"
    fn_046:    asciz "harpsichord/046.wav"
    fn_047:    asciz "harpsichord/047.wav"
    fn_048:    asciz "harpsichord/048.wav"
    fn_049:    asciz "harpsichord/049.wav"
    fn_050:    asciz "harpsichord/050.wav"
    fn_051:    asciz "harpsichord/051.wav"
    fn_052:    asciz "harpsichord/052.wav"
    fn_053:    asciz "harpsichord/053.wav"
    fn_054:    asciz "harpsichord/054.wav"
    fn_055:    asciz "harpsichord/055.wav"
    fn_056:    asciz "harpsichord/056.wav"
    fn_057:    asciz "harpsichord/057.wav"
    fn_058:    asciz "harpsichord/058.wav"
    fn_059:    asciz "harpsichord/059.wav"
    fn_060:    asciz "harpsichord/060.wav"
    fn_061:    asciz "harpsichord/061.wav"
    fn_062:    asciz "harpsichord/062.wav"
    fn_063:    asciz "harpsichord/063.wav"
    fn_064:    asciz "harpsichord/064.wav"
    fn_065:    asciz "harpsichord/065.wav"
    fn_066:    asciz "harpsichord/066.wav"
    fn_067:    asciz "harpsichord/067.wav"
    fn_068:    asciz "harpsichord/068.wav"
    fn_069:    asciz "harpsichord/069.wav"
    fn_070:    asciz "harpsichord/070.wav"
    fn_071:    asciz "harpsichord/071.wav"
    fn_072:    asciz "harpsichord/072.wav"
    fn_073:    asciz "harpsichord/073.wav"
    fn_074:    asciz "harpsichord/074.wav"
    fn_075:    asciz "harpsichord/075.wav"
    fn_076:    asciz "harpsichord/076.wav"
    fn_077:    asciz "harpsichord/077.wav"
    fn_078:    asciz "harpsichord/078.wav"
    fn_079:    asciz "harpsichord/079.wav"
    fn_080:    asciz "harpsichord/080.wav"
    fn_081:    asciz "harpsichord/081.wav"
    fn_082:    asciz "harpsichord/082.wav"
    fn_083:    asciz "harpsichord/083.wav"
    fn_084:    asciz "harpsichord/084.wav"
    fn_085:    asciz "harpsichord/085.wav"
    fn_086:    asciz "harpsichord/086.wav"
    fn_087:    asciz "harpsichord/087.wav"
    fn_088:    asciz "harpsichord/088.wav"
