
num_samples:    equ 78

; Sample dictionary (pointer, bufferId)
sample_dictionary:
    dl fn_025
    db 25
    dl fn_026
    db 26
    dl fn_027
    db 27
    dl fn_028
    db 28
    dl fn_029
    db 29
    dl fn_030
    db 30
    dl fn_031
    db 31
    dl fn_032
    db 32
    dl fn_033
    db 33
    dl fn_034
    db 34
    dl fn_035
    db 35
    dl fn_036
    db 36
    dl fn_037
    db 37
    dl fn_038
    db 38
    dl fn_039
    db 39
    dl fn_040
    db 40
    dl fn_041
    db 41
    dl fn_042
    db 42
    dl fn_043
    db 43
    dl fn_044
    db 44
    dl fn_045
    db 45
    dl fn_046
    db 46
    dl fn_047
    db 47
    dl fn_048
    db 48
    dl fn_049
    db 49
    dl fn_050
    db 50
    dl fn_051
    db 51
    dl fn_052
    db 52
    dl fn_053
    db 53
    dl fn_054
    db 54
    dl fn_055
    db 55
    dl fn_056
    db 56
    dl fn_057
    db 57
    dl fn_058
    db 58
    dl fn_059
    db 59
    dl fn_060
    db 60
    dl fn_061
    db 61
    dl fn_062
    db 62
    dl fn_063
    db 63
    dl fn_064
    db 64
    dl fn_065
    db 65
    dl fn_066
    db 66
    dl fn_067
    db 67
    dl fn_068
    db 68
    dl fn_069
    db 69
    dl fn_070
    db 70
    dl fn_071
    db 71
    dl fn_072
    db 72
    dl fn_073
    db 73
    dl fn_074
    db 74
    dl fn_075
    db 75
    dl fn_076
    db 76
    dl fn_077
    db 77
    dl fn_078
    db 78
    dl fn_079
    db 79
    dl fn_080
    db 80
    dl fn_081
    db 81
    dl fn_082
    db 82
    dl fn_083
    db 83
    dl fn_084
    db 84
    dl fn_085
    db 85
    dl fn_086
    db 86
    dl fn_087
    db 87
    dl fn_088
    db 88
    dl fn_089
    db 89
    dl fn_090
    db 90
    dl fn_091
    db 91
    dl fn_092
    db 92
    dl fn_093
    db 93
    dl fn_094
    db 94
    dl fn_095
    db 95
    dl fn_096
    db 96
    dl fn_097
    db 97
    dl fn_098
    db 98
    dl fn_099
    db 99
    dl fn_100
    db 100
    dl fn_101
    db 101
    dl fn_102
    db 102

; Sample filename strings
sample_filenames:
    fn_025:    asciz "piano/025.wav"
    fn_026:    asciz "piano/026.wav"
    fn_027:    asciz "piano/027.wav"
    fn_028:    asciz "piano/028.wav"
    fn_029:    asciz "piano/029.wav"
    fn_030:    asciz "piano/030.wav"
    fn_031:    asciz "piano/031.wav"
    fn_032:    asciz "piano/032.wav"
    fn_033:    asciz "piano/033.wav"
    fn_034:    asciz "piano/034.wav"
    fn_035:    asciz "piano/035.wav"
    fn_036:    asciz "piano/036.wav"
    fn_037:    asciz "piano/037.wav"
    fn_038:    asciz "piano/038.wav"
    fn_039:    asciz "piano/039.wav"
    fn_040:    asciz "piano/040.wav"
    fn_041:    asciz "piano/041.wav"
    fn_042:    asciz "piano/042.wav"
    fn_043:    asciz "piano/043.wav"
    fn_044:    asciz "piano/044.wav"
    fn_045:    asciz "piano/045.wav"
    fn_046:    asciz "piano/046.wav"
    fn_047:    asciz "piano/047.wav"
    fn_048:    asciz "piano/048.wav"
    fn_049:    asciz "piano/049.wav"
    fn_050:    asciz "piano/050.wav"
    fn_051:    asciz "piano/051.wav"
    fn_052:    asciz "piano/052.wav"
    fn_053:    asciz "piano/053.wav"
    fn_054:    asciz "piano/054.wav"
    fn_055:    asciz "piano/055.wav"
    fn_056:    asciz "piano/056.wav"
    fn_057:    asciz "piano/057.wav"
    fn_058:    asciz "piano/058.wav"
    fn_059:    asciz "piano/059.wav"
    fn_060:    asciz "piano/060.wav"
    fn_061:    asciz "piano/061.wav"
    fn_062:    asciz "piano/062.wav"
    fn_063:    asciz "piano/063.wav"
    fn_064:    asciz "piano/064.wav"
    fn_065:    asciz "piano/065.wav"
    fn_066:    asciz "piano/066.wav"
    fn_067:    asciz "piano/067.wav"
    fn_068:    asciz "piano/068.wav"
    fn_069:    asciz "piano/069.wav"
    fn_070:    asciz "piano/070.wav"
    fn_071:    asciz "piano/071.wav"
    fn_072:    asciz "piano/072.wav"
    fn_073:    asciz "piano/073.wav"
    fn_074:    asciz "piano/074.wav"
    fn_075:    asciz "piano/075.wav"
    fn_076:    asciz "piano/076.wav"
    fn_077:    asciz "piano/077.wav"
    fn_078:    asciz "piano/078.wav"
    fn_079:    asciz "piano/079.wav"
    fn_080:    asciz "piano/080.wav"
    fn_081:    asciz "piano/081.wav"
    fn_082:    asciz "piano/082.wav"
    fn_083:    asciz "piano/083.wav"
    fn_084:    asciz "piano/084.wav"
    fn_085:    asciz "piano/085.wav"
    fn_086:    asciz "piano/086.wav"
    fn_087:    asciz "piano/087.wav"
    fn_088:    asciz "piano/088.wav"
    fn_089:    asciz "piano/089.wav"
    fn_090:    asciz "piano/090.wav"
    fn_091:    asciz "piano/091.wav"
    fn_092:    asciz "piano/092.wav"
    fn_093:    asciz "piano/093.wav"
    fn_094:    asciz "piano/094.wav"
    fn_095:    asciz "piano/095.wav"
    fn_096:    asciz "piano/096.wav"
    fn_097:    asciz "piano/097.wav"
    fn_098:    asciz "piano/098.wav"
    fn_099:    asciz "piano/099.wav"
    fn_100:    asciz "piano/100.wav"
    fn_101:    asciz "piano/101.wav"
    fn_102:    asciz "piano/102.wav"
