"""Emit the compile-time layout contract and portable visual review worksheet."""
import json,shutil,html
from pathlib import Path

def emit_profile(d,ui,output,project,colour):
    widgets={w['name']:w for w in d['widgets']};p=d['playlist'];rows=[widgets['w_row'+str(i)]['y'] for i in range(10)]
    # Palette index matches the retained stock mode-20 mapping.
    values={'ui_path_columns':widgets['w_path']['n'],'ui_track_columns':widgets['w_track']['n'],
      'ui_filename_offset':p['filename_offset'],'ui_filename_columns':p['filename_columns'],
      'ui_has_count':int('w_count' in widgets),'ui_has_row_duration':int(p['duration_offset'] is not None),
      'ui_duration_offset':p['duration_offset'] or 0,'ui_row_wide_jumps':int(p['duration_offset'] is not None),
      'ui_pointer_table':int(rows!=list(range(88,208,12))),'ui_pointer_enabled':int(d['selection']['enabled']),
      'ui_pointer_x':d['selection']['x'],'ui_pointer_initial_y':88 if d['id'] in ('artdeco','seventies') else rows[0],
      'ui_normal_bg_value':colour(d['palette']['background']),'ui_progress_span':d['progress_span']}
    (ui/'profile.inc').write_text('; Generated layout contract; no emitted bytes.\n'+''.join(f'{k}: equ {v}\n' for k,v in values.items()))
    asm=output/'src/asm';asm.mkdir(parents=True,exist_ok=True)
    # The only skin-specific entry point is generated; all executable logic is shared.
    (asm/f"app_{d['id']}.asm").write_text(f'''; Generated by the schema compiler.
skin_custom: equ 1
skin_artdeco: equ 1
skin_seventies: equ 0
live_test_mode: equ 0
    include "../ui/{d['id']}/profile.inc"
    include "jukebox_modules.inc"
    include "../ui/{d['id']}/widgets.inc"
    include "jukebox_start.inc"
''') if d['id'] not in ('artdeco','seventies') else None

def emit_review(d,definition,review,output):
    source=definition.parent/d['source'];shutil.copy2(source,review/'source-reference.png')
    views=[['1 · Compiled preview','preview.png'],['2 · Prepared backdrop','backdrop.png'],['3 · Source artwork','source-reference.png'],['4 · Test expectation','test-paused.png']]
    from PIL import Image
    colors=sorted(set(Image.open(review/'preview.png').convert('RGB').get_flattened_data()))
    data=json.dumps(views);palette=json.dumps(['#%02x%02x%02x'%c for c in colors])
    page='''<!doctype html><meta charset="utf-8"><title>SKIN review</title><style>body{background:#181818;color:#eee;font:16px system-ui;margin:24px}button,select{font:inherit;padding:8px;margin:4px;background:#333;color:#fff;border:1px solid #888}header{position:sticky;top:0;background:#181818;padding:8px}#viewport{overflow:auto;max-height:78vh}img{display:block;image-rendering:pixelated;max-width:none}a{color:#fc8}.swatch{display:inline-block;width:24px;height:20px;margin:3px;border:1px solid #777}</style><h1>SKIN · schema review</h1><p>Generated from one skin definition. Preview and test expectation are host renders, not screenshots. Select a view, toggle comparison, or inspect target pixels.</p><header><div id="buttons"></div><select id="zoom"><option value="fit">Fit width</option><option value="512">Target 512×384</option><option value="1448">Source-sized 1448×1086</option><option value="1024">2× target</option><option value="2048">4× target</option></select><button id="toggle">Toggle previous view</button><a id="full">Full image</a><div id="colors"></div></header><div id="viewport"><img id="art"></div><script>const views=VIEWS;let current=0,previous=2;const art=document.getElementById('art'),zoom=document.getElementById('zoom');function size(){art.style.width=zoom.value==='fit'?'100%':zoom.value+'px'}function show(i){if(i!==current){previous=current;current=i}art.src=views[i][1];document.getElementById('full').href=art.src;size()}views.forEach((v,i)=>{let b=document.createElement('button');b.textContent=v[0];b.onclick=()=>show(i);document.getElementById('buttons').append(b)});zoom.onchange=size;document.getElementById('toggle').onclick=()=>show(previous);PALETTE.forEach(c=>{let s=document.createElement('span');s.className='swatch';s.title=c;s.style.background=c;document.getElementById('colors').append(s)});show(0)</script>'''
    (review/'index.html').write_text(page.replace('SKIN',html.escape(d['id'])).replace('VIEWS',data).replace('PALETTE',palette))

def emit_test_bindings(d,ui,output):
    """Bindings for the existing 26-scenario harness; no generated test logic."""
    if d['id'] in ('artdeco','seventies'):return
    from PIL import Image
    widgets={w['name']:w for w in d['widgets']}
    # Pick a guaranteed restored margin, independent of font strokes.
    lines=['    if live_test_mode']
    for label,file in [('lt_font_draw','font-probe.vdu'),('lt_font_samples','font-samples.bin'),('lt_samples','widget-samples.bin')]:
        lines += [f'{label}: incbin "../../tests/fixtures/{d["id"]}/{file}"',f'{label}_end:']
    lines += [f'    include "../ui/{d["id"]}/test-meta.inc"']
    def sample(label,x,y,color):
        lines.extend([label+':',f'    ld bc,{x}',f'    ld de,{y}'])
        for i,c in enumerate(color):lines.extend([f'    ld a,{c}',f'    ld (lt_rgb+{i}),a'])
        lines.append('    jp lt_pixel')
    # 0,0 is covered by the static background, outside all approved widget bounds.
    sample('lt_schema_frame_pixel',0,0,d['_corner'])
    for index,key in [(0,'background'),(1,'selection')]:
        w=widgets['w_row'+str(index)];sample('lt_schema_row'+str(index),w['rect'][0],w['y'],d['palette'][key])
    lines.append('    endif')
    with (ui/'widgets.inc').open('a') as f:f.write('\n'.join(lines)+'\n')
    test=output/'tests/asm';test.mkdir(parents=True,exist_ok=True)
    text=(output/'src/asm'/f'app_{d["id"]}.asm').read_text().replace('live_test_mode: equ 0','live_test_mode: equ 1')
    (test/f'{d["id"]}_check.asm').write_text(text)
