"""Bounded runtime-v1 descriptor and skin-independent assembly data generation.

The descriptor contains only scalars; VDP commands are constructed by the app.
Run after the authoring compiler to export a runtime package alongside prototypes.
"""
from pathlib import Path
import argparse, json, shutil, struct
TEXT = ['w_path','w_page','w_count']+[f'w_row{i}' for i in range(10)]+['w_message','w_track','w_elapsed','w_duration','w_detail','w_voltext']
ART = ['w_play','w_shuffle','w_loop','w_volume','w_progress','w_marker']
ART_CODES = [128,131,133,146,147,148]
MAGIC=b'JBSKIN1\0'
HEADER=32
GEOMETRY=HEADER
ART_START=GEOMETRY+len(TEXT)*15
IMAGES=ART_START+24
TILES=IMAGES+214*4
SIZE=TILES+192
ROOT=Path(__file__).resolve().parents[2]

def export(skin, output):
    from validate import load_definition
    d=load_definition(ROOT/f'src/skins/{skin}/skin.json')
    info=json.loads((ROOT/f'src/skins/{skin}/generated/build.json').read_text())
    from compile import colour
    # Runtime v1 assigns its owned image IDs by role, then decorative tiles.
    order=['idle','pause','play','shuffle_off','shuffle_on','loop_off','loop_on']+[f'volume_{i}' for i in range(12)]+['progress_track','progress_marker','selection_pointer']
    assets=info['assets']
    if [a['name'] for a in assets[:22]]!=order:
        raise ValueError('runtime v1 requires canonical control order; reorder assets and rebuild')
    if not 22<=len(assets)<=214 or sum(a['width']*a['height'] for a in assets)>262144:
        raise ValueError('runtime v1 image count or 256 KiB bitmap budget exceeded')
    if any(not 1<=a['width']<=512 or not 1<=a['height']<=64 for a in assets):
        raise ValueError('runtime v1 image dimensions exceed 512x64')
    if any((a['width'],a['height'])!=(32,32) for a in assets[22:]):
        raise ValueError('runtime v1 decorative images must be 32x32')
    w={a['name']:a for a in d['widgets']}
    buf=bytearray(SIZE);buf[:8]=MAGIC
    buf[8:20]=bytes([len(info['assets']),w['w_path']['n'],w['w_track']['n'],
        d['playlist']['filename_offset'],d['playlist']['filename_columns'],
        255 if d['playlist']['duration_offset'] is None else d['playlist']['duration_offset'],
        int(d['selection']['enabled']),colour(d['palette']['background']),
        colour(d['palette']['text']),colour(d['palette']['selection']),
        colour(d['palette']['selected_text']),d['progress_span']])
    struct.pack_into('<H',buf,20,d['selection']['x'])
    for i,name in enumerate(TEXT):
        a=w.get(name)
        if a is None:continue
        x,y,rw,rh=a['rect']
        struct.pack_into('<6H3B',buf,GEOMETRY+i*15,a['x'],a['y'],x,y,x+rw-1,y+rh-1,a['n'],colour(a['bg']),colour(a['fg']))
    for i,name in enumerate(ART):struct.pack_into('<HH',buf,ART_START+i*4,w[name]['x'],w[name]['y'])
    for i,a in enumerate(info['assets']):struct.pack_into('<HH',buf,IMAGES+i*4,a['width'],a['height'])
    buf[TILES:]=bytes([255])*192
    ids={a['name']:i for i,a in enumerate(info['assets'])}
    for p in info['placements']:buf[TILES+p['y']//32*16+p['x']//32]=ids[p['name']]
    target=output/skin;shutil.copytree(ROOT/f'skins/{skin}',target,dirs_exist_ok=True)
    manifest=(target/'skin.cfg').read_text().splitlines();manifest[0]='format=jukebox-runtime1'
    (target/'skin.cfg').write_text('\n'.join(manifest)+'\n')
    (target/'layout.bin').write_bytes(buf)
    print(f'{target}: {len(buf)} layout bytes')

def assembly():
    """Generate fixed role storage and constant VDP templates, never skin data."""
    from compile import context,font,fill,clear_buffer,word
    ui=ROOT/'src/ui/runtime';ui.mkdir(exist_ok=True)
    constants={'rt_size':SIZE,'rt_geometry':GEOMETRY,'rt_art':ART_START,'rt_images':IMAGES,'rt_tiles':TILES,
       'ui_has_count':1,'ui_has_row_duration':1,'ui_row_wide_jumps':1,'ui_pointer_table':1,'ui_pointer_enabled':1,
       'ui_normal_bg_value':0,'ui_pointer_x':0,'ui_pointer_initial_y':0,'ui_row_columns':58,'ui_normal_context':3,'ui_selected_context':4,
       'ui_idle_play_code':128,'art_play':130,'art_pause':129,'art_shuffle_off':131,'art_shuffle_on':132,
       'art_loop_off':133,'art_loop_on':134,'art_playing':129,'art_paused':130,'sa_playlist_image_count':190}
    (ui/'profile.inc').write_text('; Generated by runtime.py; skin-independent ABI.\n'+''.join(f'{k}: equ {v}\n' for k,v in constants.items()))
    s=['; Generated fixed slots; runtime geometry is read from layout.bin.']
    for name in TEXT+ART:
        s += [f'{name}: blkb 96,32',f'{name}_size: dl 0',f'{name}_len: equ 94' if name.startswith('w_row') else f'{name}_len: equ 0']
        for slot,off in ({'context':4,'bg':14,'fg':29,'text':36,'digits':36} if name in TEXT else {'x':7,'code':11}).items():s.append(f'{name}_{slot}: equ {name}+{off}')
        s += [f'{name}_send:',f'    ld hl,{name}',f'    ld bc,({name}_size)','    ld a,b','    or c','    ret z','    jp ui_send']
    s+=['rt_widget_table:']+[f'    dl {n}' for n in TEXT+ART]
    s+=['ui_rows:']+[f'    dl w_row{i},w_row{i}_text' for i in range(10)]
    s+=['w_hint_text: blkb 15,32','w_hint_send: ret','w_mode_code: db 0','w_mode_send: ret','w_thumb_x: dw 0','w_thumb_send: ret','ui_volume_x: blkb 12,0','ui_volume_codes: db '+','.join(str(i) for i in range(135,147)),
         'ui_selection_y: blkb 10,0','sa_image_meta: blkb 2354,0','ui_static: blkb 2200,0','rt_static_len: dl 0',
         'rt_descriptor: blkb rt_size,0','rt_progress_origin: dl 0']
    fields={'image_count':8,'path_columns':9,'track_columns':10,'filename_offset':11,'filename_columns':12,'duration_offset':13,'pointer_enabled':14,'normal_bg_value':15,'normal_fg':16,'selected_bg':17,'selected_fg':18,'progress_span':19}
    s += [f'rt_{k}: equ rt_descriptor+{v}' for k,v in fields.items()]
    for label,data in [('rt_text_template',context(1)+font(0x21f0)+bytes([18,0,0,25,4,0,0,0,0,25,101,0,0,0,0,18,0,0,25,4,0,0,0,0])),('rt_art_template',context(2)+bytes([25,4,0,0,0,0,128])+context(1))]:
        s.append(label+': db '+','.join(map(str,data)))
    # Map all 128 reserved art codes. Only referenced/loaded IDs are drawn.
    common=context(1)+bytes([23,0,200,2,79,5,23,0,192,0,23,16,64,0])+font(0x21f0)+bytes([23,1,0])
    ctx=common+bytes([23,0,200,1,2])+context(2)+font(65535)
    ctx+=b''.join(bytes([23,0,146,128+i])+word(0x2100+i) for i in range(128))+context(1)
    playlist=[]
    for n,base in [(3,0x2300),(4,0x2400)]:
        ctx+=context(1)+bytes([23,0,200,1,n])+context(n)+font(0x21f1)
        for i in range(95):
            ctx+=bytes([23,0,146,32+i])+word(base+i)
            playlist.append(struct.pack('<HHHBI',base+i,6,12,1,72))
    ctx+=context(1)
    cleanup=bytes([23,27,4,0,23,27,12,23,27,5,23,27,7,0,23,27,15])+context(0)+font(65535)+b''.join(bytes([23,0,200,1,n]) for n in (1,2,3,4))
    cleanup+=b''.join(bytes([23,0,149,4])+word(n) for n in (0x21f0,0x21f1))
    cleanup+=b''.join(clear_buffer(n) for n in list(range(0x2100,0x2100+214))+list(range(0x2300,0x235f))+list(range(0x2400,0x245f))+[0x21f0,0x21f1,0x2200])
    for label,file,data in [('sa_contexts','contexts.vdu',ctx),('sa_cleanup','cleanup.vdu',cleanup),('sa_playlist_image_meta','playlist-meta.bin',b''.join(playlist))]:
        (ui/file).write_bytes(data);s += [f'{label}: incbin "../ui/runtime/{file}"',f'{label}_end:']
    (ui/'widgets.inc').write_text('\n'.join(s)+'\n')

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--output-root',type=Path,default=ROOT/'skins/runtime');p.add_argument('--skin',action='append');a=p.parse_args()
    assembly()
    for skin in a.skin or ('artdeco','seventies'):
        import re
        if not re.fullmatch(r'[a-z][a-z0-9_]{0,23}',skin):p.error('invalid skin id')
        export(skin,a.output_root)
